---
title: "Natalie Karavarsamis, PhD"
output: 
  html_document:
      theme: spacelab
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

## Contact Details <br> 
Dr Natalie Karavarsamis 

1. Lecturer 

Department of Mathematics and Statistics 

La Trobe University 

Melbourne, Victoria, Australia 

Email: n.karavarsamis@latrobe.edu.au 


2. Honorary Fellow

School of Mathematics and Statistics

University of Melbourne

Victoria, Australia 

Email: nkarav@unimelb.edu.au

---

## Brief Bio
My extensive teaching, research and consulting experience that commenced a decade before my PhD candidature. My career spans two decades of experience, knowledge and acquisition of skills. Experience working in a number of statistical research areas, statistical consulting, statistical teaching and academic practice has provided me with versatility to conduct research, collaborate, supervise and teach across a broad range of statistics disciplines. These include medical statistics, primary industries, ecological statistical research and neuroscience. I am enthusiastic, and continue contributions to the body of statstical work with my expertise to progress and develop methods in these and other areas of statistics and its applications. 

---

## Curriculum Vitae

[Download Here](natalie-karavarsamis.github.io/KaravarsamisCV-2018.pdf)

---

## Professional Service & Outreach

[Choose Maths at la Trobe](natalie-karavarsamis.github.io/CHOOSEMATHS_comes_to_La_Trobe-Intranet.pdf)

---


